In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
    ]

In [7]:
np.array(my_list3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [17]:
np.random.rand(2)

array([0.36334277, 0.71936109])

In [18]:
np.random.rand(5,5)

array([[0.62825131, 0.99902673, 0.35615377, 0.88799501, 0.3093084 ],
       [0.30761736, 0.39381353, 0.03974796, 0.58604957, 0.9120044 ],
       [0.34941303, 0.05276733, 0.56977943, 0.55419924, 0.23734644],
       [0.72406859, 0.4141431 , 0.08437925, 0.38647008, 0.78659455],
       [0.51201117, 0.73372573, 0.25091545, 0.63107333, 0.76621526]])

In [19]:
np.random.randint(1,100)

11

In [20]:
np.random.randint(1,100,10)

array([58,  1, 33, 13, 31, 43, 42, 50, 61, 57])

In [21]:
my_list2 = [[1,2,3],[4,5,6],[7,8,9]]

In [22]:
array_1d = np.array(my_list)
array_2d = np.array(my_list2)
array_3d = np.array(my_list3)

In [23]:
array_1d.shape

(3,)

In [24]:
array_2d.shape

(3, 3)

In [25]:
array_3d.shape

(3, 3, 3)

In [26]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr.shape

(25,)

In [28]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [29]:
arr.reshape(1,25).shape

(1, 25)

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [32]:
arr.reshape(25,1).shape

(25, 1)

In [33]:
array_2d.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
array_2d.reshape(-1).shape

(9,)

In [35]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [36]:
array_3d.reshape(-1).shape

(27,)

In [37]:
ranarr = np.random.randint(0,50,10)

In [38]:
ranarr

array([ 8, 27, 38, 10, 12, 22, 47, 23, 44,  8])

In [39]:
ranarr.max()

47

In [40]:
ranarr.argmax()

6

In [41]:
ranarr.min()

8

In [42]:
ranarr.argmin()

0

In [43]:
ranarr.mean()

23.9

In [44]:
arr.dtype

dtype('int64')

In [45]:
arr1 = np.linspace(0,10,10)
arr1.dtype

dtype('float64')

In [46]:
arr1

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [48]:
x = np.arange(0,25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
x[17] #get a value at an index

17

In [51]:
x[1:7] #get velues in a range

array([1, 2, 3, 4, 5, 6])

In [52]:
x[0:5]

array([0, 1, 2, 3, 4])

In [53]:
x[0:10:3]

array([0, 3, 6, 9])

In [54]:
x[0:5] = 100
x

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [55]:
x = np.arange(0,25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
slicingx = x[0:6]
slicingx

array([0, 1, 2, 3, 4, 5])

In [57]:
slicingx[:] = 99
slicingx

array([99, 99, 99, 99, 99, 99])

In [58]:
x

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [60]:
x_copy = x.copy()
x_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
array_2d[1]

array([4, 5, 6])

In [64]:
array_2d[2][0]

7

In [67]:
array_2d[2,0]

7

In [68]:
array_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [70]:
array_2d[:,2]

array([3, 6, 9])

In [72]:
x = np.arange(0,25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [73]:
[x[2],x[5],x[9]]

[2, 5, 9]

In [74]:
x[[2,5,9]]

array([2, 5, 9])

In [75]:
x[[9,3,10]]

array([ 9,  3, 10])

In [76]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
array_2d[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [78]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [79]:
x < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [80]:
x[x<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])